// Run with node tests/board_regression.cjs; no dependencies required.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('map_template.html','utf8');
const extract=(start,end)=>src.slice(src.indexOf(start),src.indexOf(end,src.indexOf(start)));
const ctx=vm.createContext({Date,performance,Map,matchMedia:()=>({matches:true}),requestAnimationFrame:()=>{}});
vm.runInContext(`const AIRPORTS={};const LIVE={rows:[]};let REPLAY=false;const tk=()=> '2026-09-15';const hkDate=()=> '2026-09-16';const fresh=()=>false;`+extract('function statusOf(r)','function rowGate(r)'),ctx);
vm.runInContext(`LIVE.rows=[{dir:'D',date:'2026-09-10',time:'12:00',f:'CX1',dest:'LHR',status:'Dep 12:10'}];`,ctx);
assert.equal(vm.runInContext("boardRows('D').length",ctx),0);
vm.runInContext('REPLAY=true',ctx);
assert.equal(vm.runInContext("boardRows('D').length",ctx),1,'Replay must retain archived flights');
vm.runInContext(extract('function setTile(t,ch)','let AC=null'),ctx);
vm.runInContext(`const tile={dataset:{ch:' '},_disp:' ',_ts:{},_bs:{},_ft:{}};qFlip(tile,'A',500);qFlip(tile,'B',0);qstep(performance.now()+1000);`,ctx);
assert.equal(vm.runInContext('tile._disp',ctx),'B','Delayed flip must not overwrite a newer value');
assert.equal(vm.runInContext('tile.dataset.ch',ctx),'B');
assert.equal(vm.runInContext('Q.length',ctx),0,'Completed flip queue must be released');
console.log('Passed: archive dates, completed archive flights, stale flip cancellation, queue cleanup');
const elements={};const element=id=>elements[id]||(elements[id]={innerHTML:'',textContent:'',checked:true});
let layers=new Set();
const layer=()=>({addTo(){layers.add(this);return this},bindTooltip(){return this}});
const mapStub={setView(){return this},removeLayer(l){layers.delete(l)}};
const approachContext=vm.createContext({document:{getElementById:element},L:{map:()=>mapStub,tileLayer:layer,geoJSON:layer,polyline:layer,circleMarker:layer},DATA:{geo:{},geo3d:{rwy:[[[113.9,22.3],[113.91,22.31]]]},taxigraph:{thrs:Array(6)},nav:[],origins:{LHR:{la:51,lo:0}}},LIVE:{trails:[],rows:[{dir:'D',date:'2026-09-15',dest:'LHR'}]},STYLE:{},tk:()=> '2026-09-15',drawTrails:()=>{}});
vm.runInContext(extract('let FLOWMAP=null','let THREEREADY='),approachContext);
vm.runInContext('initFlow();drawArcs();',approachContext);
const layerCount=layers.size;
vm.runInContext('drawArcs();drawArcs();',approachContext);
assert.equal(layers.size,layerCount,'Revisiting approaches must not accumulate route layers');
vm.runInContext('ARCS=false;drawArcs();',approachContext);
assert.equal(layers.size,layerCount-1,'Disabling routes removes the layer without a constant assignment error');
assert.equal((src.match(/function flightPanel\(/g)||[]).length,1,'Flight details must not be shadowed');
console.log('Passed: approaches initialization, route cleanup/toggle, unique flight panel');
const saved={watchlist:JSON.stringify({CX1:1}),watchstate:'{}'};
const watchContext=vm.createContext({localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v},LIVE:{rows:[{f:'CX1',date:'2026-09-15',gate:'1',status:'Boarding'}]},tk:()=> '2026-09-15',arrGate:()=>'',Notification:{permission:'denied'},renderWx:()=>{}});
vm.runInContext(extract('function watchList()','function toggleWatch(f)'),watchContext);
vm.runInContext('checkWatch()',watchContext);
assert.equal(JSON.parse(saved.watchstate).CX1.gate,'1','Initial watch baseline must be persisted');
console.log('Passed: watch baseline persistence');
